ALTER TABLE "Ride" ADD COLUMN IF NOT EXISTS "passengerReadyAt" TIMESTAMP(3);
ALTER TABLE "Ride" ADD COLUMN IF NOT EXISTS "passengerLat" TEXT;
ALTER TABLE "Ride" ADD COLUMN IF NOT EXISTS "passengerLng" TEXT;
